global:
  scrape_interval: 1s

scrape_configs:
- job_name: dubbo_provider
  metrics_path: /metrics
  static_configs:
  - targets:
    - 'host.docker.internal:9464'
- job_name: dubbo_customer
  metrics_path: /metrics
  static_configs:
  - targets:
    - 'host.docker.internal:9465'
